name: Package & Release

# The workflow to build and release official Kong packages and images.

on:  # yamllint disable-line rule:truthy
  pull_request:
  push:
    branches:
    - main
    - next/*
    - release/*
  workflow_dispatch:

jobs:
  job:
    name: Job
    runs-on: ubuntu-latest
    steps:
    - name: Step One
      run: |
        n="$(shuf -i 3-10 -n 1)"

        echo "sleeping for ${n} seconds"

        sleep $n

    - name: Randomly Fail
      env:
        VERBOSE: ${{ runner.debug }}
      run: |
        n="$(shuf -i 0-1 -n 1)"

        if [ $n -eq 0 ]; then
          echo "ding dong, all is well"
        else
          echo "trouble is afoot!"
        fi

        if [ -n "$VERBOSE" ]; then
          echo "succeeding because debug was enabled"
          exit 0
        else
          exit $n
        fi
