name: Package & Release

# The workflow to build and release official Kong packages and images.

on:  # yamllint disable-line rule:truthy
  pull_request:
  push:
    branches:
    - main
    - next/*
    - release/*
  workflow_dispatch:

jobs:
  job:
    name: Job
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Step One
      run: |
        sleep "$(shuf -i 3-10 -n 1)"

    - name: Randomly Fail
      run: |
        exit "$(shuf -i 0-1 -n 1)"
